name: "my_dbt_project"
version: "1.0.0"

profile: "my_dbt_profile" # Mantenemos tu perfil actual

model-paths: ["models"] # carpeta donde están los archivos .sql
target-path: "target" # carpeta que se crea con SQL compilado y resultado de ejecuciones
clean-targets: # indica que carpetas se van a borrar cuando se ejecute dbt clean
  - "target"
  - "dbt_packages"

# --- NUEVA CONFIGURACIÓN DE MODELOS ---
models:
  my_dbt_project:
    # Capa de limpieza: se crean como vistas para no duplicar datos físicamente
    staging:
      +materialized: view
      +schema: staging
    # Capa de negocio: se crean como tablas para que las consultas sean rápidas
    core:
      +materialized: table
      +schema: core
